export const ACTION_CHANGE_TAB = 'ACTION_CHANGE_TAB';

export const ACTION_FETCH_DATA = 'ACTION_FETCH_DATA';

export const HIDDEN_LOADING = 'HIDDEN_LOADING';

export const SHOW_LOADING = 'SHOW_LOADING';

export const APP_UPGRADE = 'APP_UPGRADE';

export const LOAD_USER = 'LOAD_USER';

export const APP_USER_LOGOUT = 'APP_USER_LOGOUT';

export const GET_COMPANY_AUTH_FETAIL = 'GET_COMPANY_AUTH_FETAIL';

export const ACTION_UPDATE_OSS_CONFIG = 'ACTION_UPDATE_OSS_CONFIG';

export const ACTION_MESSAGE_LIST = 'ACTION_MESSAGE_LIST';

export const MSG_SELECT_ONE_OF_DATAS = 'MSG_SELECT_ONE_OF_DATAS';

export const MESSAGE_CHECKED_ALL = 'MESSAGE_CHECKED_ALL';

export const UPDATE_MSG_LIST = 'UPDATE_MSG_LIST';

export const ACTION_REFRESH_MESSAGE_LIST = 'ACTION_REFRESH_MESSAGE_LIST';

export const ACTION_CHECKBOX = 'ACTION_CHECKBOX';

export const ACTION_CLEAR_ALL_SELECT = 'ACTION_CLEAR_ALL_SELECT';

export const ACTION_MSG_DETAIL = 'ACTION_MSG_DETAIL';

export const ACTION_USER_INFO = 'ACTION_USER_INFO';

export const ACTION_MERGE_USER = 'ACTION_MERGE_USER';

export const ACTION_CHANGE_CENTER = 'ACTION_CHANGE_CENTER';

export const ACTION_RECEIVE_ORDER_LIST = 'ACTION_RECEIVE_ORDER_LIST'

export const ACTION_CHANGE_ORDER_TOP_TAB = 'ACTION_CHANGE_ORDER_TOP_TAB'

export const ACTION_RECEIVE_ORDER_DETAIL = 'ACTION_RECEIVE_ORDER_DETAIL'

export const ACTION_RECIEVE_CONSIGNO = 'ACTION_RECIEVE_CONSIGNO'

export const ACTION_REFRESH_CONSIGNOR = 'ACTION_REFRESH_CONSIGNOR';

export const ACTION_GOODS_RESOURCE_DETAIL = 'ACTION_GOODS_RESOURCE_DETAIL';

export const ACTION_CLEAN_RESOURCE_DETAIL = 'ACTION_CLEAN_RESOURCE_DETAIL';

export const ACTION_SHIPPER_LIST = 'ACTION_SHIPPER_LIST';

export const ACTION_SHIPPER_REFRESH = 'ACTION_SHIPPER_REFRESH';

export const ACTION_CONSIGNOR_DETAIL_REFRESH = 'ACTION_CONSIGNOR_DETAIL_REFRESH';

export const ACTION_GET_INVOICE_DETAIL = 'ACTION_GET_INVOICE_DETAIL';

export const ACTION_ORDER_TO_STATE_WITH_ORDERNO = 'ACTION_ORDER_TO_STATE_WITH_ORDERNO'

export const ACTION_SHOULE_ORDER_LIST_REFRESH = 'ACTION_SHOULE_ORDER_LIST_REFRESH'

export const ACTION_REFRESH_ESIGN_TEMPLATE_INFO = 'ACTION_REFRESH_ESIGN_TEMPLATE_INFO';

export const ACTION_REFRESH_ESIGN_COLOR_INFO = 'ACTION_REFRESH_ESIGN_COLOR_INFO';

export const GET_PERSON_AUTH_DETAIL = 'GET_PERSON_AUTH_DETAIL';

export const ACTION_GET_PUBLISH_ONTIME_ROUTE = 'ACTION_GET_PUBLISH_ONTIME_ROUTE';

export const ACTION_GET_PUBLISH_ONTIME_DETAIL = 'ACTION_GET_PUBLISH_ONTIME_DETAIL';

export const ACTION_GET_START_TIME = 'ACTION_GET_START_TIME';

export const ACTION_GET_FRIGHT_MONEY = 'ACTION_GET_FRIGHT_MONEY';

export const ACTION_CLEAR_MONEY = 'ACTION_CLEAR_MONEY';

export const ACTION_ISCABANID = 'ACTION_ISCABANID';

export const ACTION_GET_CARRIER_ROUTE = 'ACTION_GET_CARRIER_ROUTE';

export const ACTION_ISSTARTDATE = 'ACTION_ISSTARTDATE';

export const ACTION_CACHE_SIZE = 'ACTION_CACHE_SIZE';

export const ACTION_GET_MSG = 'ACTION_GET_MSG';

export const ACTION_CLEAR_DATA = 'ACTION_CLEAR_DATA';

export const RESET_HAS_MORE_CONSIGNRO = 'RESET_HAS_MORE_CONSIGNRO';

export const ACTION_RECEIVE_CONFIRM_CLEAR_DETAIL = 'ACTION_RECEIVE_CONFIRM_CLEAR_DETAIL';

export const ACTION_PHONE_REGISTER_RESULT = 'ACTION_PHONE_REGISTER_RESULT';

export const ACTION_H5_GAME_URL = 'ACTION_H5_GAME_URL'

export const ACTION_REDICT_LOGIN = 'ACTION_REDICT_LOGIN'
