export const ACTION_CHANGE_TAB = 'ACTION_CHANGE_TAB';

export const ACTION_FETCH_DATA = 'ACTION_FETCH_DATA';

export const HIDDEN_LOADING = 'HIDDEN_LOADING';

export const SHOW_LOADING = 'SHOW_LOADING';

export const APP_UPGRADE = 'APP_UPGRADE';

export const LOAD_USER = 'LOAD_USER';

export const APP_USER_LOGOUT = 'APP_USER_LOGOUT';

export const OOS_CONFIG = 'OOS_CONFIG';

export const ACTION_CITY_COUNTRY = 'ACTION_CITY_COUNTRY';

export const ACTION_DISPATCH_CARBIND_DRIVER = 'ACTION_DISPATCH_CARBIND_DRIVER';

export const ACTION_REFRESH_CAR = 'ACTION_REFRESH_CAR';

export const ACTION_SELECT_DRIVER = 'ACTION_SELECT_DRIVER';


export const ACTION_GET_CAR_INTO = 'ACTION_GET_CAR_INTO';

export const ACTION_SYSTEM_MESSAGE = 'ACTION_SYSTEM_MESSAGE';

export const MSG_SELECT_ONE_OF_DATAS = 'MSG_SELECT_ONE_OF_DATAS';

export const ACTION_SYSTEM_MSG_DETAIL = 'ACTION_SYSTEM_MSG_DETAIL';

export const MESSAGE_CHECKED_ALL = 'MESSAGE_CHECKED_ALL';

export const UPDATE_MSG_LIST = 'UPDATE_MSG_LIST';

export const ACTION_ROUTE_LIST = 'ACTION_ROUTE_LIST';

export const ACTION_GET_AUTHINFO_DETAIL = 'ACTION_GET_AUTHINFO_DETAIL';

export const ACTION_GET_FEEDBACK_LIST = 'ACTION_GET_FEEDBACK_LIST';

export const ACTION_GET_PROBLEM_LIST = 'ACTION_GET_PROBLEM_LIST';

export const ACTION_GET_FEEDBACL_DETAILS = 'ACTION_GET_FEEDBACL_DETAILS';

export const ACTION_GET_PROBLEM_DETAILS = 'ACTION_GET_PROBLEM_DETAILS';

export const ACTION_UPDATE_FEEDBACK_LIST = 'ACTION_UPDATE_FEEDBACK_LIST';

export const ACTION_SELECT_CAR = 'ACTION_SELECT_CAR';

export const ACTION_REFRESH_ADD_ROUTE = 'ACTION_REFRESH_ADD_ROUTE';

export const ACTION_REFRESH_DELETE_ROUTE = 'ACTION_REFRESH_DELETE_ROUTE';

export const ACTION_REFRESH_DRIVER = 'ACTION_REFRESH_DRIVER';

export const ACTION_WEB_MSG_LIST = 'ACTION_WEB_MSG_LIST';


export const ACTION_GET_NORMAL_ROUTE_LIST = 'ACTION_GET_NORMAL_ROUTE_LIST'

export const ACTION_RECEIVE_GOODS_LIST = 'ACTION_RECEIVE_GOODS_LIST'

export const ACTION_RECEIVE_BETTER_GOODS_LIST = 'ACTION_RECEIVE_BETTER_GOODS_LIST'

export const ACTION_RECEIVE_GOODS_DETAIL = 'ACTION_RECEIVE_GOODS_DETAIL'

export const ACTION_GET_ENTRUST_ORDER_LIST = 'ACTION_GET_ENTRUST_ORDER_LIST'


export const ACTION_GET_FREE_CAR_LIST = 'ACTION_GET_FREE_CAR_LIST'

export const ACTION_RECEIVE_PRE_ORDER_LIST = 'ACTION_RECEIVE_PRE_ORDER_LIST'

export const ACTION_RECEIVE_ENTRUST_ORDER_DETAIL = 'ACTION_RECEIVE_ENTRUST_ORDER_DETAIL'

export const ACTION_RECEIVE_ENTRUST_ORDER_DETAIL_TRANSPORTCONFIRM = 'ACTION_RECEIVE_ENTRUST_ORDER_DETAIL_TRANSPORTCONFIRM'

export const ACTION_RECEIVE_ORDER_LIST = 'ACTION_RECEIVE_ORDER_LIST'

export const ACTION_CONTACT_MESSAGE = 'ACTION_CONTACT_MESSAGE'

export const ACTION_CARS_ORDER_WORK = 'ACTION_CARS_ORDER_WORK';

export const ACTION_TRAVEL_DATA = 'ACTION_TRAVEL_DATA';

export const ACTION_ROUTE_DEFAULT_CAR = 'ACTION_ROUTE_DEFAULT_CAR';

export const ACTION_COMPANY = 'ACTION_COMPANY';

export const ACTION_REFRESH_MESSAGE_LIST = 'ACTION_REFRESH_MESSAGE_LIST';

export const ACTION_RECEIVE_ORDER_DETAIL = 'ACTION_RECEIVE_ORDER_DETAIL'


export const ACTION_ORDER_TO_STATE_WITH_ORDERNO = 'ACTION_ORDER_TO_STATE_WITH_ORDERNO'

export const ACTION_GET_ESIGN_INTO = 'ACTION_GET_ESIGN_INTO';

export const ACTION_REFRESH_ESIGN_TEMPLATE_INFO = 'ACTION_REFRESH_ESIGN_TEMPLATE_INFO';

export const ACTION_REFRESH_ESIGN_COLOR_INFO = 'ACTION_REFRESH_ESIGN_COLOR_INFO';

export const ACTION_MERGE_USER = 'ACTION_MERGE_USER';

export const ACTION_BARGAIN_LIST = 'ACTION_BARGAIN_LIST';


export const ACTION_UPDATE_OSS_CONFIG = 'ACTION_UPDATE_OSS_CONFIG';

export const ACTION_CHANGE_ORDER_LOADINGMORE = 'ACTION_CHANGE_ORDER_LOADINGMORE'

export const ACTION_CHANGE_ENTRUST_ORDER_LIST_LOADING_MORE = 'ACTION_CHANGE_ENTRUST_ORDER_LIST_LOADING_MORE'

export const ACTION_CHANGE_GOODS_LIST_LOADING_MORE = 'ACTION_CHANGE_GOODS_LIST_LOADING_MORE'


export const ACTION_SET_ALL_UNPAY_SELECTED_OR_NOT = 'ACTION_SET_ALL_UNPAY_SELECTED_OR_NOT'

export const ACTION_SET_UNPAY_ORDER_BATCH_EDITING = 'ACTION_SET_UNPAY_ORDER_BATCH_EDITING'

export const ACTION_CHANGE_SELECT_STATE_IN_UNPAY_ORDER = 'ACTION_CHANGE_SELECT_STATE_IN_UNPAY_ORDER'

export const ACTION_RECEIVE_CLEAR_DETAIL = 'ACTION_RECEIVE_CLEAR_DETAIL'

export const ACTION_SHOW_FLAOT_DIALOG = 'ACTION_SHOW_FLAOT_DIALOG';

export const ACTION_GET_INITED = 'ACTION_GET_INITED';

export const ACTION_CARRIER_DETAIL = 'ACTION_CARRIER_DETAIL';

export const ACTION_ACCEPT_DESIGNATE_WITH_ID = 'ACTION_ACCEPT_DESIGNATE_WITH_ID';

export const ACTION_CHANGE_ORDER_TOP_TAB = 'ACTION_CHANGE_ORDER_TOP_TAB'

export const ACTION_GOODS_SOURCE_END_COUNT = 'ACTION_GOODS_SOURCE_END_COUNT'

export const ACTION_CHECKBOX = 'ACTION_CHECKBOX'

export const ACTION_CONFIG_BILL_OUT_IMAGE_FOR_ORDER = 'ACTION_CONFIG_BILL_OUT_IMAGE_FOR_ORDER'

export const ACTION_REFRESH_DRIVER_INFO = 'ACTION_REFRESH_DRIVER_INFO'

export const ACTION_CLEAR_DRIVER_INFO = 'ACTION_CLEAR_DRIVER_INFO'


export const ACTION_ALIAS = 'ACTION_ALIAS';

export const ACTION_COMBINE_STATUS = 'ACTION_COMBINE_STATUS'

export const ACTION_CLEAR_AUTH_INFO = 'ACTION_CLEAR_AUTH_INFO'

export const ACTION_SHOULD_ENTRUST_ORDER_LIST_REFRESH = 'ACTION_SHOULD_ENTRUST_ORDER_LIST_REFRESH'

export const ACTION_NOTIFICATION = 'ACTION_NOTIFICATION';

export const ACTION_SET_APPSTATE = 'ACTION_SET_APPSTATE';

export const ACTION_CLEAR_IMG_SOURCE = 'ACTION_CLEAR_IMG_SOURCE'

export const ACTION_SHOULE_ORDER_LIST_REFRESH = 'ACTION_SHOULE_ORDER_LIST_REFRESH';

export const ACTION_COMBINEIMG = 'ACTION_COMBINEIMG'

export const ACTION_REFRESH_TRAVEL = 'ACTION_REFRESH_TRAVEL';

export const ACTION_CLEAR_ALL_SELECT = 'ACTION_CLEAR_ALL_SELECT';

export const ACTION_CLEAR_ROUTE_INFO = 'ACTION_CLEAR_ROUTE_INFO';

export const ACTION_REDICT_LOGIN = 'ACTION_REDICT_LOGIN';

export const ACTION_LOGIN_SUCCESS = 'ACTION_LOGIN_SUCCESS';

export const ACTION_GET_PERSONAL_AUTHINFO_DETAIL = 'ACTION_GET_PERSONAL_AUTHINFO_DETAIL';

export const ACTION_SELECT_BANK_CARD_LIST = 'ACTION_SELECT_BANK_CARD_LIST';

export const ACTION_REFRESH_BANK_CARD = 'ACTION_REFRESH_BANK_CARD';

export const ACTION_SELECT_BANK_CARD_BY_ID = 'ACTION_SELECT_BANK_CARD_BY_ID';

export const UPGRADE_FORCE = 'UPGRADE_FORCE';

export const UPGRADE_FORCE_HIDDEN = 'UPGRADE_FORCE_HIDDEN';

export const ACTION_GET_DRIVER_INFO = 'ACTION_GET_DRIVER_INFO';

export const ACTION_DRIVER_INFO_DETAIL = 'ACTION_DRIVER_INFO_DETAIL';

export const ACTION_GET_GAME_URL = 'ACTION_GET_GAME_URL'

export const ACTION_DELETE_UNDISPATCH_CANCELLED_ORDER = 'ACTION_DELETE_UNDISPATCH_CANCELLED_ORDER'

export const ACTION_REMOVE_OVERTIME_ORDER_FROM_LIST = 'ACTION_REMOVE_OVERTIME_ORDER_FROM_LIST'

export const ACTION_CHANGE_GOODS_LIST_IS_REFRESHING = 'ACTION_CHANGE_GOODS_LIST_IS_REFRESHING'

export const CARLENGTH_SELECT_ONE_OF_DATAS = 'CARLENGTH_SELECT_ONE_OF_DATAS';

export const ACTION_GET_CARLENGTH = 'ACTION_GET_CARLENGTH'

export const ACTION_SELECTED_CARLENGTH = 'ACTION_SELECTED_CARLENGTH'

export const ACTION_TRAVEL_DONE = 'ACTION_TRAVEL_DONE'

export const ACTION_RECEIVE_IN_SITE_NOTICE = 'ACTION_RECEIVE_IN_SITE_NOTICE'

export const ACTION_APPEND_LOG = 'ACTION_APPEND_LOG'

export const ACTION_WRITE_LOG = 'ACTION_WRITE_LOG'

export const ACTION_RESET_AD = 'ACTION_RESET_AD'

export const ACTION_CHANGE_ENTRUST_ORDER_LIST_REFRESHING = 'ACTION_CHANGE_ENTRUST_ORDER_LIST_REFRESHING'

export const ACTION_CHANGE_ORDER_LIST_REFRESHING = 'ACTION_CHANGE_ORDER_LIST_REFRESHING'

export const ACTION_CHANGE_PRE_ORDER_LIST_REFRESHING = 'ACTION_CHANGE_PRE_ORDER_LIST_REFRESHING'

export const ACTION_CHANGE_ORDER_URGED_WITH_ORDER_NO = 'ACTION_CHANGE_ORDER_URGED_WITH_ORDER_NO'

export const ACTION_SET_DRIVER_CHARACTER = 'ACTION_SET_DRIVER_CHARACTER'; // 账户-司机角色

export const ACTION_SET_OWNER_CHARACTER = 'ACTION_SET_OWNER_CHARACTER'; // 账户-车主角色

export const ACTION_SET_COMPANY_CODE = 'ACTION_SET_COMPANY_CODE'; // companyCode

export const ACTION_SET_CURRENT_CHARACTER = 'ACTION_SET_CURRENT_CHARACTER'; // 账户-当前选择角色

export const ACTION_QUERY_ENTER_PRISE_NATURE = 'ACTION_QUERY_ENTER_PRISE_NATURE';   // 查询司机对应企业性质

export const ACTION_SAVE_USER_CAR_LIST = 'ACTION_SAVE_USER_CAR_LIST';// 主界面点击事件

/*用户名*/
export const ACTION_USER_NAME = 'ACTION_USER_NAME';

// 车主名称
export const ACTION_OWNER_NAME = 'ACTION_OWNER_NAME';

/*用户绑定车辆发生改变*/
export const ACTION_USER_CAR = 'ACTION_USER_CAR';
/*清空user里面的值*/
export const ACTION_USER_CLEAR = 'ACTION_USER_CLEAR';

export const ACTION_TOGGLE_LOADING = 'ACTION_TOGGLE_LOADING'