
export const ROUTE_MESSAGE_LIST = 'ROUTE_MESSAGE_LIST';

export const ROUTE_CONSIGNOR_MANAGER = 'ROUTE_CONSIGNOR_MANAGER';

//注册
export const ROUTE_REGISTER = 'ROUTE_REGISTER';

//公司认证详情
export const ROUTE_COMPANYAUTH_DETAIL = 'ROUTE_COMPANYAUTH_DETAIL';

//公司认证
export const ROUTE_COMPANYAUTH = 'ROUTE_COMPANYAUTH';

//发布干线
export const ROUTE_PUBLISH_GROUDLINE = 'ROUTE_PUBLISH_GROUDLINE';

//重新发布干线
export const ROUTE_AGAIN_PUBLISH_GROUPLINE = 'ROUTE_AGAIN_PUBLISH_GROUPLINE';

//我的电子签章
export const ROUTE_SHOW_ESIGN_IMAGE = 'ROUTE_SHOW_ESIGN_IMAGE';

//公司电子签章
export const ROUTE_UPDATE_COMPANY_ESIGN_INFO = 'ROUTE_UPDATE_COMPANY_ESIGN_INFO';

//个人电子签章
export const ROUTE_UPDATE_PERSON_ESIGN_INFO = 'ROUTE_UPDATE_PERSON_ESIGN_INFO';

//选择地址
export const ROUTE_SELECT_ADDRESS = 'ROUTE_SELECT_ADDRESS';

//选择温度
export const ROUTE_SELECT_TEMPAREYURE = 'ROUTE_SELECT_TEMPAREYURE';

//测试
export const ROUTE_TEST = 'ROUTE_TEST';

export const ROUTE_FIND_ROUTE = 'ROUTE_FIND_ROUTE';

export const PASSWORD_PAGE = 'PASSWORD_PAGE';

export const PASSWORD_TWO_PAGE = 'PASSWORD_TWO_PAGE';

export const ROUTE_CONFIGNOR_DETAIL = 'ROUTE_CONFIGNOR_DETAIL';

export const ROUTE_SETTING_PAGE = 'ROUTE_SETTING_PAGE';

export const ROUTE_SHIPPER = 'ROUTE_SHIPPER';

export const ROUTE_MESSAGE_DETAIL= 'ROUTE_MESSAGE_DETAIL';


export const ROUTE_ORDER_DETAIL = 'ROUTE_ORDER_DETAIL'

export const ROUTE_UPLOAD_IMAGES = 'ROUTE_UPLOAD_IMAGES'

export const ROUTE_CONTRACT_DETAIL = 'ROUTE_CONTRACT_DETAIL'

export const ROUTE_LOGIN = 'ROUTE_LOGIN';

export const ROUTE_PERSON_AUTH_INFO = 'ROUTE_PERSON_AUTH_INFO';

export const ROUTE_PERSON_AUTH_PAGE = 'ROUTE_PERSON_AUTH_PAGE';

export const ROUTE_PUBLISH_ONTIME_PAGE = 'ROUTE_PUBLISH_ONTIME_PAGE';

export const ROUTE_INVOICE_INFO_PAGE = 'ROUTE_INVOICE_INFO_PAGE';

export const ROUTE_COMMON_INVOICE = 'ROUTE_COMMON_INVOICE';

export const ROUTE_PUBLISH_CONFIGNOR = 'ROUTE_PUBLISH_CONFIGNOR'

export const ROUTE_CONFIRM_CLEAR = 'ROUTE_CONFIRM_CLEAR'

export const ROUTE_APPLY_COORDINATION = 'ROUTE_APPLY_COORDINATION'

export const ROUTE_UPDATE_PASSAGE = 'ROUTE_UPDATE_PASSAGE';

export const ROUTE_SELECT_ONTIME_ROUTE = 'ROUTE_SELECT_ONTIME_ROUTE';

export const ROUTE_IMAGES_REVIEW = 'ROUTE_IMAGES_REVIEW';

export const ROUTE_AGAIN_PUBLISH_ONTIME = 'ROUTE_AGAIN_PUBLISH_ONTIME';

export const ROUTE_ABOUT_US = 'ROUTE_ABOUT_US';

export const ROUTE_CALCULATE_PRICE = 'ROUTE_CALCULATE_PRICE';

export const ROUTE_AGREEMENT_CONTENT = 'ROUTE_AGREEMENT_CONTENT';

export const ROUTE_GAME = 'ROUTE_GAME'
