export const ROUTE_LOGIN = 'ROUTE_LOGIN';

export const ROUTE_CAR_LIST = 'ROUTE_CAR_LIST';

export const ROUTE_MESSAGE_DETAIL = 'ROUTE_MESSAGE_DETAIL';

export const ROUTE_ROUTES_LIST = 'ROUTE_ROUTES_LIST';

export const ROUTE_DISPATCH_CAR = 'ROUTE_DISPATCH_CAR';

export const ROUTE_CONFIRM_DELIVERY = 'ROUTE_CONFIRM_DELIVERY';

export const ROUTE_APPLY_COORDINATION = 'ROUTE_APPLY_COORDINATION';

export const ROUTE_REFUSE_DESIGNATE = 'ROUTE_REFUSE_DESIGNATE';

export const ROUTE_LADING_BILL = 'ROUTE_LADING_BILL';

export const ROUTE_BIDDING_LIST = 'ROUTE_BIDDING_LIST';

export const ROUTE_PRE_ORDER = 'ROUTE_PRE_ORDER';

export const ROUTE_RULE_INSTRUCTION = 'ROUTE_RULE_INSTRUCTION';

// export const ROUTE_GRAB_MANAGER = 'ROUTE_GRAB_MANAGER';
export const ROUTE_ORDER_DETAIL = 'ROUTE_ORDER_DETAIL';

export const ROUTE_ENTRUST_ORDER_DETAIL = 'ROUTE_ENTRUST_ORDER_DETAIL';

export const ROUTE_TRANSPORT_CONFIRM = 'ROUTE_TRANSPORT_CONFIRM'

export const ROUTE_BILL_DETAIL = 'ROUTE_BILL_DETAIL'

export const ROUTE_CONTRACT_DETAIL = 'ROUTE_CONTRACT_DETAIL'

export const ROUTE_SEARCH_GOODS = 'ROUTE_SEARCH_GOODS'

export const ROUTE_MY_ROUTE = 'ROUTE_MY_ROUTE';

export const ROUTE_MY_CAR = 'ROUTE_MY_CAR';

export const ROUTE_SETTING = 'ROUTE_SETTING';

export const ROUTE_ADD_CAR = 'ROUTE_ADD_CAR';

export const ROUTE_USER_INFO = 'ROUTE_USER_INFO';

export const ROUTE_COMPANY_AUTH = 'ROUTE_COMPANY_AUTH';

export const ROUTE_CUSTOME_SERVICE = 'ROUTE_CUSTOME_SERVICE';

export const ROUTE_HELP = 'ROUTE_HELP';

export const ROUTE_REGISTER = 'ROUTE_REGISTER';

export const ROUTE_REGISTER_PWD = 'ROUTE_REGISTER_PWD';

export const ROUTE_DRIVER_MANAGER = 'ROUTE_DRIVER_MANAGER';

export const ROUTE_ADD_DRIVER = 'ROUTE_ADD_DRIVER';

export const ROUTE_ADD_ROUTE = 'ROUTE_ADD_ROUTE';

export const ROUTE_HELP_DETAIL = 'ROUTE_HELP_DETAIL';

export const ROUTE_HELP_DETAIL_FOR_FEEDBACK = 'ROUTE_HELP_DETAIL_FOR_FEEDBACK';

export const ROUTE_ADD_FEEDBACK = 'ROUTE_ADD_FEEDBACK';

export const ROUTE_AUTH_INFO = 'ROUTE_AUTH_INFO';

export const ROUTE_BARGAIN = 'ROUTE_BARGAIN';

export const ROUTE_BARGAIN_DETAILS = 'ROUTE_BARGAIN_DETAILS';

export const ROUTE_CAR_BIND_DRIVER = 'ROUTE_CAR_BIND_DRIVER';

export const ROUTE_SELECTED_DRIVER = 'ROUTE_SELECTED_DRIVER';

export const ROUTE_CAR_DETAIL = 'ROUTE_CAR_DETAIL';

export const ROUTE_EDIT_CAR = 'ROUTE_EDIT_CAR';

export const ROUTE_MESSAGE_LIST = 'ROUTE_MESSAGE_LIST';

export const ROUTE_CAR_LOGIN = 'ROUTE_CAR_LOGIN';

export const ROUTE_PASSWORD_PAGE = 'ROUTE_PASSWORD_PAGE';

export const ROUTE_PASSWORD_TWO_PAGE = 'ROUTE_PASSWORD_TWO_PAGE';

export const ROUTE_EDIT_ROUNT_PAGE = 'ROUTE_EDIT_ROUNT_PAGE';

export const ROUTE_FILL_CONTACT_MESSAGE_PAGE = 'ROUTE_FILL_CONTACT_MESSAGE_PAGE';

export const ROUTE_REGISTER_PHONE_PAGE = 'ROUTE_REGISTER_PHONE_PAGE';

export const ROUTE_INVOICE_EXPLANATION = 'ROUTE_INVOICE_EXPLANATION';

export const ROUTE_SHOW_ESIGN_IMAGE = 'ROUTE_SHOW_ESIGN_IMAGE';

export const ROUTE_UPDATE_ESIGN_INFO = 'ROUTE_UPDATE_ESIGN_INFO';

export const ROUTE_COMPANY_LIST = 'ROUTE_COMPANY_LIST';

export const ROUTE_UPLOAD_IMAGES = 'ROUTE_UPLOAD_IMAGES';

export const ROUTE_ABOUT_US = 'ROUTE_ABOUT_US';

export const ROUTE_SERVICE_PROVISION = 'ROUTE_SERVICE_PROVISION';

export const ROUTE_NEW_ROUTE = 'ROUTE_NEW_ROUTE';

export const ROUTE_AUTH_ROLE = 'ROUTE_AUTH_ROLE';

export const ROUTE_PERSONAL_AUTH = 'ROUTE_PERSONAL_AUTH';

export const ROUTE_PERSONAL_AUTH_DETAIL = 'ROUTE_PERSONAL_AUTH_DETAIL';

export const ROUTE_BANK_CARD_LIST = 'ROUTE_BANK_CARD_LIST';

export const ROUTE_ADD_BANK_CARD = 'ROUTE_ADD_BANK_CARD';

export const ROUTE_AGREEMENT_CONTENT = 'ROUTE_AGREEMENT_CONTENT';

export const ROUTE_DRIVER_INFO_DETAIL = 'ROUTE_DRIVER_INFO_DETAIL';

export const ROUTE_GAME_PAGE = 'ROUTE_GAME_PAGE';

// 司机首页
export const ROUTE_DRIVER_HOME_PAGE = 'ROUTE_DRIVER_HOME_PAGE';
// 司机货源
export const ROUTE_DRIVER_GOOD_PAGE = 'ROUTE_DRIVER_GOOD_PAGE';
// 司机订单
export const ROUTE_DRIVER_ORDER_PAGE = 'ROUTE_DRIVER_ORDER_PAGE';
// 我的页面
export const ROUTE_MINE_PAGE = 'ROUTE_MINE_PAGE';
// 账号密码登录页
export const ROUTE_LOGIN_WITH_PWD_PAGE = 'ROUTE_LOGIN_WITH_PWD_PAGE';
// 短信验证码登录
export const ROUTE_LOGIN_WITH_SMS_PAGE = 'ROUTE_LOGIN_WITH_SMS_PAGE';
// 修改密码
export const ROUTE_MODIFY_PWD = 'ROUTE_MODIFY_PWD';
